DATA SEGMENT
  STR1 DB 'HELLO! CYBERPUNK 2077',0DH,0AH,'$'
DATA ENDS

CODE SEGMENT
  ASSUME CS:CODE,DS:DATA
START:
      MOV AX,DATA
      MOV DS,AX
      MOV DX,OFFSET STR1
      MOV AH,9
      INT 21H;输出字符串
      MOV AH,4CH
      INT 21H
CODE ENDS
 END START